### ISSUE TITLE
A config to disable mobs from registering

### ISSUE THREAD

**Issue by knoxhack** [X-Niter/DTM-Integrations#16]
A config option to disable mobs from getting registered in the game before loading instead of just removing it from spawning.

Mostly need this because there are 3 different mods I'm trying to use that they all add bandit mobs and they have the same internal name. The game doesn't start because of that.

Another good option will be to rename the bandits internal name

**Comment by X-Niter** [comment]
@knoxhack , other than what I might say in discord, there is a fine line on if registries can be modified like that, as yes that is possible, but now we are getting into the discussion of ASM needs potentially in order to put an If catcher inside the registry. 

Also, all mobs inside the registry are registered "modid:modname" so I am a bit confused on how the game is not loading because of the same names, last I recalled, mods can have the same names but still be different registries and won't conflict.

**Comment by knoxhack** [comment]
this is the crash that I'm getting:

[https://raw.githubusercontent.com/NFINIT-Development/Planetary/master/crash-2022-08-31_16.57.22-client.txt](https://raw.githubusercontent.com/NFINIT-Development/Planetary/master/crash-2022-08-31_16.57.22-client.txt)

**Comment by X-Niter** [comment]
> this is the crash that I'm getting:
> 
> https://raw.githubusercontent.com/NFINIT-Development/Planetary/master/crash-2022-08-31_16.57.22-client.txt

What's the mods combined that cause this to happen?

**Comment by knoxhack** [comment]
> > this is the crash that I'm getting:
> > https://raw.githubusercontent.com/NFINIT-Development/Planetary/master/crash-2022-08-31_16.57.22-client.txt
> 
> What's the mods combined that cause this to happen?

It happens when 7DTM and [https://www.curseforge.com/minecraft/mc-mods/efw-forgotten-place](https://www.curseforge.com/minecraft/mc-mods/efw-forgotten-place)  are prensent
